yandex/mysync

internal/app/app.go
Old master may have uncommitted transactions (ex. waiting for semy-sync) at the moment we set him read-only.
When we turn off semi-senc replication - these transactions may become commited.
Client application will know nothing about these transactions, but we will have splitbrain here.
We should wait till old master become read-only here
=> Wait host become read-only before remove 'recovery'

internal/app/app.go
The old master may not pick up the binlog file from the master because of this, a large data lag appears. Before that, such replicas did not belong to the becomeInactive category, now they will and semi sync will be turned off correctly on the old master
=> fix: semi sync does not turn off on the old master

internal/app/app.go, internal/app/replication.go, internal/config/config.go, internal/mysql/node.go, internal/mysql/replication.go, internal/util/consts.go, tests/images/mysql/mysync.yaml
I want to make "strategy" pattern with `IExternalReplication` in `app`. To reach this purpose I made `UnimplementedExternalReplication` which contain empty methods and `ExternalReplication` which contain `Node` methods.
=> External replication refactoring

internal/mysql/cluster.go, internal/mysql/data.go, internal/mysql/node.go, internal/mysql/util.go, internal/util/consts.go
- Changed 'Disable' constant to improve readability
- Structs optimized
- Removed duplication in `queryRowWithTimeout` and `queryRows`
- Other small changes
Used golangci-lint to detect alignment mistakes in structures: https://golangci-lint.run/usage/install/
Use it with `config.yaml`:
```
linters:
  enable:
    - maligned
```
Run it: `golangci-lint run ./... --config ./config.yaml`
=> Small refactoring

internal/util/util.go, tests/images/base/setup.sh
Issue:
3.7.1 version of Apache Zookeeper, which is used in tests, was moved to the archives.
Failed tests:
- [Failed test - mysql 8.0](https://github.com/yandex/mysync/actions/runs/6483012385/job/17604723760)
- [Failed test - mysql 5.7](https://github.com/yandex/mysync/actions/runs/6483012383/job/17603676800)
=> Apache Zookeeper download link fix

internal/app/replication.go
When a long query runs on a replication with an error, then mysync
1. Tries to repair it with some algorithm.
2. Waits some time.
3. Checks that IO and SQL are running.
4. It thinks that replication is fixed, but in fact, when replaying such a transaction, replication may break again. This will be repeated forever until someone notices the mistake.
Detailed steps to reproduce: https://gist.github.com/noname0443/d2a42845dc34a39c9a34a038f0b974cd
I changed the repair algorithm:
1. Remember the current GTID for the channel we want to repair.
2. Try to repair it with some algorithm.
3. Wait for some time.
4. Check that IO and SQL are running and GTID has changed.
5. Replication is fixed.
=> Bug fix for replication repair on long queries

internal/app/app.go, internal/config/config.go
add repl_mon chech in async mode
=> add repl_mon chech in async mode

internal/app/app.go, internal/app/replication.go, internal/app/util.go, internal/app/util_test.go, internal/mysql/gtids/utils.go, internal/mysql/gtids/wrapper.go
When replicas return to active nodes it may be streaming binlog. If binlog is big enough and we restart replication - we will interrupt download process. So we should restart only replicas ahead, as they have all required binary logs
=> restart only replicas ahead of the master

internal/app/app.go, internal/mysql/switch_helper.go
add failoverQuorum semisync check, refactor failoverQuorum
=> [WIP] add failoverQuorum semisync check, refactor failoverQuorum

README.md, internal/app/app.go, internal/config/config.go, internal/mysql/node.go, tests/features/switchover_from.feature, tests/features/switchover_to.feature, tests/images/mysql/mysync.yaml
This PR aims to fix the switchover when a lot of connections try to change data. MySync can't kill them fast enough and fails to complete the switchover.
1. Run the script:
```bash
docker rm -f $(docker ps -aq)
cd ../../
GOOS=linux go build -tags netgo,osusergo -o ./tests/images/mysql/mysync ./cmd/mysync/...
docker build --tag=mysync-test-base8.0 tests/images/base --build-arg MYSQL_VERSION=8.0
cd tests/images/
VERSION=8.0 docker-compose up --build -d
docker rm -f images-mysql3-1
docker cp images_zoo1_1:/etc/zk-ssl/ca.cert.pem .
docker cp images_zoo1_1:/etc/zk-ssl/server.crt .
docker cp images_zoo1_1:/etc/zk-ssl/server.key .
docker exec -it images_mysql1_1 mkdir -p /etc/zk-ssl
docker exec -it images_mysql2_1 mkdir -p /etc/zk-ssl
docker cp ca.cert.pem images_mysql1_1:/etc/zk-ssl/
docker cp …
```
=> Fix switchover when many connections appear

tests/images/jepsen_main/jepsen/src/jepsen/mysync.clj
attemp to fix error "set was never read"
=> fix jepsen timeout

internal/app/app.go, internal/app/cli.go, internal/app/data.go, internal/app/data_test.go
Stringer interface is broken for NodeState, so if we print map[string]*NodeState, it prints hosts with pointers.
Before this PR
```bash
2024-10-09T09:57:34Z INFO: cs: map[mysql1:0xc00025c2a0 mysql2:0xc0001a03f0 mysql3:0xc0000ae380]
2024-10-09T09:57:34Z INFO: dcs cs: map[mysql1:0xc000140af0 mysql2:0xc000140b60 mysql3:0xc000182310]
```
After this PR
```bash
2024-10-09T09:51:47Z INFO: cs: map[mysql1:<ping=ok repl=error sync=--- ro=true offline=false lag=NaN du=??? cr=??? gtid=> mysql2:<ping=ERR repl=??? sync=??? ro=false offline=false lag=0.00 du=??? cr=??? gtid=???> mysql3:<ping=ERR repl=??? sync=??? ro=false offline=false lag=0.00 du=??? cr=??? gtid=???>]
2024-10-09T09:51:47Z INFO: dcs cs: map[mysql1:<ping=ok repl=error sync=--- ro=true offline=false lag=NaN du=10.00% cr=yes gtid=> …
```
=> Fix Stringer interface for NodeState

internal/app/app.go, internal/mysql/node.go, internal/mysql/queries.go
Do not show GTID in trace queries when the option is ON
=> Do not show GTID in trace queries when the option is ON

internal/app/app.go, internal/app/data.go
When we use gtid diff in health check, we should ignore the gtid field on a replica, because it doesn't know the gtid of a source and always sends `master state not defined`.
We see now:
```
INFO: healthcheck: <ping=ok repl=running sync=--s ro=true offline=false lag=0.68 du=7.84% cr=no gtid=master state not defined>
```
I changed it to:
```
INFO: healthcheck: <ping=ok repl=running sync=--s ro=true offline=false lag=0.68 du=7.84% cr=no>
```
When we request data using `getClusterStateFromDB`, we know at least information about the disk usage and the daemon state on the local node and can output it to the log file.
We see now:
```
INFO: cs: map[mysql1:<ping=ok repl=master sync=--- ro=false offline=false lag=0.00 du=??? cr=??? gtid=gtid1:1-1820834>]
INFO: dcs cs: map[mysql1:<ping=ok …
```
=> Slightly improve logging

.golangci.yml
There is an error in the last version of golangci-lint:
```
Running [/home/runner/golangci-lint-1.64.4-linux-amd64/golangci-lint run] in [/home/runner/work/mysync/mysync] ...
level=warning msg="The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar."
level=error msg="[linters_context] exportloopref: This linter is fully inactivated: it will not produce any reports."
Error: golangci-lint exit with code 7
Ran golangci-lint in 18477ms
```
=> Fix linter

internal/mysql/node.go
NewNode creates new connections on every call, causing unnecessary overhead for operations like mysync info (read-only ZK data queries).
Implement own lazy initialization like `sync.Once`
We create new connect only when we really need it.
=> [Ready for Review] Lazy initialization for nodes

internal/config/config.go, internal/mysql/node.go
Too many log in `query.log` when general_log=ON
=> Dont write general log 

cmd/mysync/maintenance.go, internal/app/cli.go, internal/app/data.go
Allow users to specify maintenance reason:
```
mysync maintenance on --reason "test maintenance"
```
and see it:
```
mysync info
...
maintenance:
initiated_at: "2025-03-21T06:17:05.961162127Z"
initiated_by: rc1a-mm25u5an15rj42ao.example.com
mysync_paused: true
reason: test maintenance
should_leave: false
```
```
mysync info -s
...
maintenance: <ON by rc1a-mm25u5an15rj42ao.example.com at 2025-03-21
06:17:05.961162127 +0000 UTC (test maintenance)>
```
=> Allow users to specify maintenance reason

internal/app/cli.go, internal/util/user.go, tests/features/async_setting.feature, tests/features/maintenance.feature, tests/features/switchover_from.feature, tests/features/zk_maintenance.feature, tests/testutil/matchers/matchers.go
Guess who runs 'mysync maintenance on' and show it in mysync info:
```
mysync maintenance on --reason "test"
maintenance enabled
```
```
mysync info
...
maintenance:
initiated_at: "2025-03-21T12:11:29.390216177Z"
initiated_by: ostinru@rc1a-mm25u5an15rj42ao.example.com      <-- HERE!
mysync_paused: true
reason: test
should_leave: false
```
=> Guess who runs 'mysync maintenance on'

internal/app/app.go, internal/app/data.go, internal/app/data_test.go
When downloading the binlog, issues may occur due to various reasons, prompting the binlog to be re-loaded. To ensure such cases are handled by duty, the isLoadingBinlog flag must be set to false when the replica is re-loading the binlog.
=> [WIP] fix IsLoadingBinlog field because flapping transactions

cmd/mysync/maintenance.go, cmd/mysync/optimize.go, internal/app/app.go, internal/app/cli_optimize.go, internal/app/cli_util.go, internal/mysql/cluster.go, internal/mysql/node.go, internal/mysql/queries.go, tests/features/CLI.feature
These changes introduce an optional 'turbo' mode to accelerate replication convergence. Enabling this mode for lagging replicas reduces their disk pressure and speeds up catch-up time with the primary node. However, this mode carries a risk of data loss and should be used with caution.
Additionally, the changes include optimization replicas with excessive lag that are no longer participating in the semi-sync process.
=> Add turbo mode to CLI

internal/app/app.go, tests/features/cascade_replicas.84.feature, tests/features/cascade_replicas.feature, tests/images/docker-compose.yaml, tests/images/mysql/mysync.yaml
When the source of a cascade replica returns after downtime, it may have a lower GTID than the cascade replica (which has been streaming from the master). While this does not cause split-brain (since the cascade replica starts only after its source has converged), it creates a redundant `mysync.emerge` file on the filesystem.
=> Fix mysync.emerge for cascade replica in case the source replica is returned after downtime

cmd/mysync/switch.go, internal/app/app.go, internal/app/app_dcs.go, internal/app/cli_switch.go, internal/app/data.go, tests/features/failover.84.feature, tests/features/failover.feature, tests/features/readonly_filesystem.feature, tests/features/switchover_from.84.feature, tests/features/switchover_from.feature, tests/features/switchover_to.feature, tests/features/zk_failure.feature
During an unstable network, the old master might repeatedly become available and then unavailable. This leads to an inconsistency between the `clusterState` (derived from MySQL) and the `activeNodes` (from Zookeeper). Specifically, if the old master is not included in the `frozenActiveNodes` set, it will not participate in the catch-up process. As a result, the new master might not have all the data that was on the old master, which can eventually lead to a split-brain scenario.
To prevent this, we could add transition type to the switchover mechanism. Switchover requires the master to be alive during the process, whereas failover does not. If an error occurs while setting the old master to read-only mode during switchover, we must reject the switchover. During failover, however, we must …
=> Do not do switchover in unstable network

internal/app/app.go
If MasterTransition is not specified - we may leave old master not read-only, that will cause splitbrain
=> MasterTransition may not be specified
